apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iu2mijph4-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:62b8f75f1f4d3436de23dec542bc924c9646d5c2@sha256:7a951accd2ca996235c920df9cfea924bcf0ebde7c5f70db64424a1d1a50b205
          name: container-image
